MasterIp: 10.142.0.58
MasterPort: 6379
ReplicaIp: localhost
ReplicaPort: 6379

LogDir: "./logs"

NReplicas: 2 # number of replicas used in the Redis WAIT command (at least replicate to NReplicas to proceed)

NServers: 3
NClients: 100
ClientTimeout: 100000
NClientRequests: 10000
ClientBatchSize: 10

KeyLen: 10
ValLen: 10