# IP of your master VM (Make sure you change this before you start server)
MasterIp: 10.128.15.204  
MasterPort: 6379
ReplicaIp: localhost
ReplicaPort: 6379

LogDir: "./logs"

NReplicas: 1 # number of replicas used in the Redis WAIT command (at least replicate to NReplicas to proceed)

NServers: 2 # number of VMs (e.g. in the case of 1 master and 1 replica, NServers = 2)
NClients: 15 # number of clients (proxy batch)
ClientTimeout: 100000
NClientRequests: 10000
ClientBatchSize: 20 # batch size for each client

KeyLen: 10
ValLen: 10
